version: '3'

services:
  dnsmasq:
    build:
      # [Copy ISO Image from docker-host]
      context: .
      dockerfile: dnsmasq/Dockerfile
      # [Download ISO Image from ubuntu.com]
      # context: ./dnsmasq/
      args:
        UBUNTU_CODENAME: ${UBUNTU_CODENAME}
    image: pxe-ubuntu/dnsmasq:${UBUNTU_CODENAME}
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq/pxe-dnsmasq.conf:/etc/dnsmasq.d/pxe-dnsmasq.conf
      - ./dnsmasq/grub.cfg:/srv/tftp/grub/grub.cfg
      - ./dnsmasq/default:/srv/tftp/legacy/pxelinux.cfg/default

  httpd:
    build:
      # [Copy ISO Image from docker-host]
      context: .
      dockerfile: ./httpd/Dockerfile
      # [Download ISO Image from ubuntu.com]
      # context: ./httpd/
      args:
        UBUNTU_CODENAME: ${UBUNTU_CODENAME}
    image: pxe-ubuntu/httpd:${UBUNTU_CODENAME}
    ports:
      - "80:80"
    volumes:
      - ./httpd/pxe-httpd.conf:/etc/apache2/conf.d/pxe-httpd.conf
      - ./httpd/autoinstall:/srv/httpd/autoinstall

